#############################################################################
# Makefile for building: SubSVT
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 10? 9 14:51:48 2020
# Project:  SubSVT.pro
# Template: subdirs
# Command: c:\Qt\Qt4.8.7-vs2015_x64\bin\qmake.exe -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o Makefile SubSVT.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Qt\Qt4.8.7-vs2015_x64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-svtpub \
		sub-TempSSCompare \
		sub-mmsmanage \
		sub-filemanage \
		sub-SubVMP

svtpub\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) svtpub\ $(MKDIR) svtpub\ 
	cd svtpub\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\svtpub\svtpub.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-svtpub-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) svtpub\ $(MKDIR) svtpub\ 
	cd svtpub\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\svtpub\svtpub.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-svtpub: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE)
sub-svtpub-make_default-ordered: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) 
sub-svtpub-make_default: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) 
sub-svtpub-make_first-ordered: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) first
sub-svtpub-make_first: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) first
sub-svtpub-all-ordered: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) all
sub-svtpub-all: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) all
sub-svtpub-clean-ordered: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) clean
sub-svtpub-clean: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) clean
sub-svtpub-distclean-ordered: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) distclean
sub-svtpub-distclean: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) distclean
sub-svtpub-install_subtargets-ordered: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) install
sub-svtpub-install_subtargets: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) install
sub-svtpub-uninstall_subtargets-ordered: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-svtpub-uninstall_subtargets: svtpub\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) uninstall
TempSSCompare\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) TempSSCompare\ $(MKDIR) TempSSCompare\ 
	cd TempSSCompare\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\TempSSCompare\TempSSCompare.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-TempSSCompare-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) TempSSCompare\ $(MKDIR) TempSSCompare\ 
	cd TempSSCompare\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\TempSSCompare\TempSSCompare.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-TempSSCompare: TempSSCompare\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE)
sub-TempSSCompare-make_default-ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-make_default-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) 
sub-TempSSCompare-make_default: TempSSCompare\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) 
sub-TempSSCompare-make_first-ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-make_first-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) first
sub-TempSSCompare-make_first: TempSSCompare\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) first
sub-TempSSCompare-all-ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-all-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) all
sub-TempSSCompare-all: TempSSCompare\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) all
sub-TempSSCompare-clean-ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-clean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) clean
sub-TempSSCompare-clean: TempSSCompare\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) clean
sub-TempSSCompare-distclean-ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-distclean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) distclean
sub-TempSSCompare-distclean: TempSSCompare\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) distclean
sub-TempSSCompare-install_subtargets-ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-install_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) install
sub-TempSSCompare-install_subtargets: TempSSCompare\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) install
sub-TempSSCompare-uninstall_subtargets-ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-uninstall_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-TempSSCompare-uninstall_subtargets: TempSSCompare\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) uninstall
mmsmanage\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) mmsmanage\ $(MKDIR) mmsmanage\ 
	cd mmsmanage\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\mmsmanage\mmsmanage.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-mmsmanage-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) mmsmanage\ $(MKDIR) mmsmanage\ 
	cd mmsmanage\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\mmsmanage\mmsmanage.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-mmsmanage: mmsmanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE)
sub-mmsmanage-make_default-ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-make_default-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) 
sub-mmsmanage-make_default: mmsmanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) 
sub-mmsmanage-make_first-ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-make_first-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) first
sub-mmsmanage-make_first: mmsmanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) first
sub-mmsmanage-all-ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-all-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) all
sub-mmsmanage-all: mmsmanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) all
sub-mmsmanage-clean-ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-clean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) clean
sub-mmsmanage-clean: mmsmanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) clean
sub-mmsmanage-distclean-ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-distclean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) distclean
sub-mmsmanage-distclean: mmsmanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) distclean
sub-mmsmanage-install_subtargets-ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-install_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) install
sub-mmsmanage-install_subtargets: mmsmanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) install
sub-mmsmanage-uninstall_subtargets-ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-uninstall_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-mmsmanage-uninstall_subtargets: mmsmanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) uninstall
filemanage\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) filemanage\ $(MKDIR) filemanage\ 
	cd filemanage\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\filemanage\filemanage.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-filemanage-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) filemanage\ $(MKDIR) filemanage\ 
	cd filemanage\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\filemanage\filemanage.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-filemanage: filemanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE)
sub-filemanage-make_default-ordered: filemanage\$(MAKEFILE) sub-mmsmanage-make_default-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) 
sub-filemanage-make_default: filemanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) 
sub-filemanage-make_first-ordered: filemanage\$(MAKEFILE) sub-mmsmanage-make_first-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) first
sub-filemanage-make_first: filemanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) first
sub-filemanage-all-ordered: filemanage\$(MAKEFILE) sub-mmsmanage-all-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) all
sub-filemanage-all: filemanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) all
sub-filemanage-clean-ordered: filemanage\$(MAKEFILE) sub-mmsmanage-clean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) clean
sub-filemanage-clean: filemanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) clean
sub-filemanage-distclean-ordered: filemanage\$(MAKEFILE) sub-mmsmanage-distclean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) distclean
sub-filemanage-distclean: filemanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) distclean
sub-filemanage-install_subtargets-ordered: filemanage\$(MAKEFILE) sub-mmsmanage-install_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) install
sub-filemanage-install_subtargets: filemanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) install
sub-filemanage-uninstall_subtargets-ordered: filemanage\$(MAKEFILE) sub-mmsmanage-uninstall_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-filemanage-uninstall_subtargets: filemanage\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) uninstall
SubVMP\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) SubVMP\ $(MKDIR) SubVMP\ 
	cd SubVMP\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\SubVMP\SubVMP.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-SubVMP-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) SubVMP\ $(MKDIR) SubVMP\ 
	cd SubVMP\ && $(QMAKE) h:\workspace\prj2017\nanwangzhinenglubo\pc\SubVMP\SubVMP.pro -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o $(MAKEFILE)
sub-SubVMP: SubVMP\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE)
sub-SubVMP-make_default-ordered: SubVMP\$(MAKEFILE) sub-filemanage-make_default-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) 
sub-SubVMP-make_default: SubVMP\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) 
sub-SubVMP-make_first-ordered: SubVMP\$(MAKEFILE) sub-filemanage-make_first-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) first
sub-SubVMP-make_first: SubVMP\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) first
sub-SubVMP-all-ordered: SubVMP\$(MAKEFILE) sub-filemanage-all-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) all
sub-SubVMP-all: SubVMP\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) all
sub-SubVMP-clean-ordered: SubVMP\$(MAKEFILE) sub-filemanage-clean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) clean
sub-SubVMP-clean: SubVMP\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) clean
sub-SubVMP-distclean-ordered: SubVMP\$(MAKEFILE) sub-filemanage-distclean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) distclean
sub-SubVMP-distclean: SubVMP\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) distclean
sub-SubVMP-install_subtargets-ordered: SubVMP\$(MAKEFILE) sub-filemanage-install_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) install
sub-SubVMP-install_subtargets: SubVMP\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) install
sub-SubVMP-uninstall_subtargets-ordered: SubVMP\$(MAKEFILE) sub-filemanage-uninstall_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-SubVMP-uninstall_subtargets: SubVMP\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: SubSVT.pro  c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default\qmake.conf c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\qconfig.pri \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\modules\qt_webkit_version.pri \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\qt_functions.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\qt_config.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\win32-msvc2015\qmake.conf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\exclusive_builds.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\default_pre.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\default_pre.prf \
		2-zxpg.pri \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\debug.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\debug_and_release.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\default_post.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\default_post.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\rtti.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\exceptions.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\stl.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\shared.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\embed_manifest_exe.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\embed_manifest_dll.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\warn_on.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\qt.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\thread.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\moc.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\windows.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\resources.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\uic.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\yacc.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\lex.prf \
		c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\include_source_dir.prf
	$(QMAKE) -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o Makefile SubSVT.pro
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\qconfig.pri:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\qt_functions.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\qt_config.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\win32-msvc2015\qmake.conf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\exclusive_builds.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\default_pre.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\default_pre.prf:
2-zxpg.pri:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\debug.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\debug_and_release.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\default_post.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\default_post.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\rtti.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\exceptions.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\stl.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\shared.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\embed_manifest_exe.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\embed_manifest_dll.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\warn_on.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\qt.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\thread.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\moc.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\win32\windows.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\resources.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\uic.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\yacc.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\lex.prf:
c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\Qt4.8.7-vs2015_x64\mkspecs\default -o Makefile SubSVT.pro

qmake_all: sub-svtpub-qmake_all sub-TempSSCompare-qmake_all sub-mmsmanage-qmake_all sub-filemanage-qmake_all sub-SubVMP-qmake_all FORCE

make_default: sub-svtpub-make_default-ordered sub-TempSSCompare-make_default-ordered sub-mmsmanage-make_default-ordered sub-filemanage-make_default-ordered sub-SubVMP-make_default-ordered FORCE
make_first: sub-svtpub-make_first-ordered sub-TempSSCompare-make_first-ordered sub-mmsmanage-make_first-ordered sub-filemanage-make_first-ordered sub-SubVMP-make_first-ordered FORCE
all: sub-svtpub-all-ordered sub-TempSSCompare-all-ordered sub-mmsmanage-all-ordered sub-filemanage-all-ordered sub-SubVMP-all-ordered FORCE
clean: sub-svtpub-clean-ordered sub-TempSSCompare-clean-ordered sub-mmsmanage-clean-ordered sub-filemanage-clean-ordered sub-SubVMP-clean-ordered FORCE
distclean: sub-svtpub-distclean-ordered sub-TempSSCompare-distclean-ordered sub-mmsmanage-distclean-ordered sub-filemanage-distclean-ordered sub-SubVMP-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-svtpub-install_subtargets-ordered sub-TempSSCompare-install_subtargets-ordered sub-mmsmanage-install_subtargets-ordered sub-filemanage-install_subtargets-ordered sub-SubVMP-install_subtargets-ordered FORCE
uninstall_subtargets: sub-svtpub-uninstall_subtargets-ordered sub-TempSSCompare-uninstall_subtargets-ordered sub-mmsmanage-uninstall_subtargets-ordered sub-filemanage-uninstall_subtargets-ordered sub-SubVMP-uninstall_subtargets-ordered FORCE

sub-svtpub-sub_Debug_ordered: svtpub\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) debug
sub-TempSSCompare-sub_Debug_ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-sub_Debug_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) debug
sub-mmsmanage-sub_Debug_ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-sub_Debug_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) debug
sub-filemanage-sub_Debug_ordered: filemanage\$(MAKEFILE) sub-mmsmanage-sub_Debug_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) debug
sub-SubVMP-sub_Debug_ordered: SubVMP\$(MAKEFILE) sub-filemanage-sub_Debug_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-svtpub-sub_Debug_ordered sub-TempSSCompare-sub_Debug_ordered sub-mmsmanage-sub_Debug_ordered sub-filemanage-sub_Debug_ordered sub-SubVMP-sub_Debug_ordered

sub-svtpub-sub_Release_ordered: svtpub\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) release
sub-TempSSCompare-sub_Release_ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-sub_Release_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) release
sub-mmsmanage-sub_Release_ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-sub_Release_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) release
sub-filemanage-sub_Release_ordered: filemanage\$(MAKEFILE) sub-mmsmanage-sub_Release_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) release
sub-SubVMP-sub_Release_ordered: SubVMP\$(MAKEFILE) sub-filemanage-sub_Release_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) release
release: sub-svtpub-sub_Release_ordered sub-TempSSCompare-sub_Release_ordered sub-mmsmanage-sub_Release_ordered sub-filemanage-sub_Release_ordered sub-SubVMP-sub_Release_ordered

sub-svtpub-check_ordered: svtpub\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd svtpub\ && $(MAKE) -f $(MAKEFILE) check
sub-TempSSCompare-check_ordered: TempSSCompare\$(MAKEFILE) sub-svtpub-check_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TempSSCompare\ && $(MAKE) -f $(MAKEFILE) check
sub-mmsmanage-check_ordered: mmsmanage\$(MAKEFILE) sub-TempSSCompare-check_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd mmsmanage\ && $(MAKE) -f $(MAKEFILE) check
sub-filemanage-check_ordered: filemanage\$(MAKEFILE) sub-mmsmanage-check_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd filemanage\ && $(MAKE) -f $(MAKEFILE) check
sub-SubVMP-check_ordered: SubVMP\$(MAKEFILE) sub-filemanage-check_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SubVMP\ && $(MAKE) -f $(MAKEFILE) check
check: sub-svtpub-check_ordered sub-TempSSCompare-check_ordered sub-mmsmanage-check_ordered sub-filemanage-check_ordered sub-SubVMP-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

